# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopEau
                                 A QGIS plugin
 Variables relatives au niveau d'eau dans les marais du projet MAVI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-15
        copyright            : (C) 2025 by Marion Bleuse
        email                : marion.bleuse8@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopEau class from file TopEau.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topeau import TopEau
    return TopEau(iface)
